
version: 0.0
# In the Resources section, you must specify the following: the Amazon ECS service, task definition name, 
# and the name and port of the load balancer to route traffic,
# target version, and (optional) the current version of your AWS Lambda function. 
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        # Specify the ARN of your task definition (arn:aws:ecs:region:account-id:task-definition/task-definition-family-name:task-definition-revision-number)
        TaskDefinition: "arn:aws:ecs:ap-southeast-1:309814440714:task-definition/frontend-task-definition:2" 
        LoadBalancerInfo: 
          ContainerName: "nodejs-container" # Specify the name of your Amazon ECS application's container
          ContainerPort: "3000" # Specify the port for your container where traffic reroutes 